### ISSUE TITLE
Plot scenarios side by side

### ISSUE THREAD

**Issue by mengqi-z** [JGCRI/rmap#16]
When having different scenarios in the 'scenario' column in the data table, the output scenario maps are not plotted side by side in one map. Instead, the maps are categorized by scenarios in each folder. The way around this is to put scenarios within the 'class' column to make one aggregated map with all the scenarios. Is there a way to keep the scenarios in the 'scenario' column and have an aggregated single plot?

**Comment by zarrarkhan** [comment]
Closed in commit: 76a7cbec9e7d6e66c977389c7db603b71db82a77
