### ISSUE TITLE
Map Projections

### ISSUE THREAD

**Issue by ejarbuck** [JGCRI/rmap#41]
Hi, this is a very impressive tool for data visualization with GCAM (and other applications)! I had a few questions for Zarrar and Chris yesterday at the GCAM Community Meeting. I have resolved how to plot data on SubRegions for Canada and have no further questions about that at this time. Another question I have is whether it might be possible to plot maps in different projections? (I think it is Mercator projection by default).

**Comment by zarrarkhan** [comment]
Thanks for the suggestion. The current projections are geographic (lat/lon) datum: WGS84. We will add a "projection" argument so you can set your own projection using a proj4string or EPSG number. 

---------------------

Yes for the Canadian provinces, I just updated rmap so it allows you to use data labels for cropped shapes. So please update to the latest version and then you can produce the provinces as well as label them as follows:

Documentation on sub-setting a shape: https://jgcri.github.io/rmap/articles/vignette_map.html#subset-existing-shape

```
library(rmap)
shapeSubset <- rmap::mapStates # Read in World States shape file
shapeSubset <- shapeSubset[shapeSubset@data$region %in% c("Canada"),] # Subset the shapefile to Canada
shapeSubset@data <- droplevels(shapeSubset@data)
rmap::map(data=shapeSubset,
          labels=T,
          labelSize = 3,
          labelFill = "white",
          labelAlpha = 0.6,
          labelRepel = 1,
          underLayer=rmap::mapCountries,
          zoom =-3) # View custom shape
```

![map (2)](https://user-images.githubusercontent.com/7863115/125692847-be4828d0-7aa7-4869-9f17-0d84c5e54d48.png)

**Comment by zarrarkhan** [comment]
@ejarbuck 
We have added functionality to change the projection. Example is here: https://jgcri.github.io/rmap/articles/vignette_map.html#projections

For your particular case:

```
library(rmap); library(dplyr)
shapeSubset <- rmap::mapStates # Read in World States shape file
shapeSubset <- shapeSubset %>% dplyr::filter(region == "Canada")
m1<-rmap::map(data=shapeSubset,
              labels=T,
              labelSize = 3,
              labelFill = "white",
              labelAlpha = 0.6,
              labelRepel = 2,
              underLayer=rmap::mapCountriesUS52,
              background=T,
              crs="+proj=lcc +lat_1=49 +lat_2=77 +lat_0=0 +lon_0=-95 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs")
```
![map](https://user-images.githubusercontent.com/7863115/159496743-53895b92-e9fd-441f-8aa6-23fa08ee69f1.png)
