### ISSUE TITLE
Bug in plotting gridded data

### ISSUE THREAD

**Issue by KennethAnn** [JGCRI/rmap#81]
Hi, when I use rmap::map(data) in user guide to plot the gridded data, the R Studio will show:
```
Error: Problem with `mutate()` column `subRegion`.
i `subRegion = as.character(subRegion)`.
i `subRegion` must be size 67420 or 1, not 0.
```

So, how to avoid the bug which seems like the hint of polygon plotting? Thanks for your kind response!

**Comment by zarrarkhan** [comment]
Thanks for pointing this out. It should be fixed now.
