### ISSUE TITLE
33-reg/basin map (with Uruguay) is at lower resolution than the standard 32-reg/basin map 

### ISSUE THREAD

**Issue by brinday** [JGCRI/rmap#89]
![image](https://user-images.githubusercontent.com/10574029/163408248-e30b1566-dd3c-4c02-8816-52f3dde011c8.png)
![image](https://user-images.githubusercontent.com/10574029/163408307-150623d8-b31a-4987-a929-631e1e0e465c.png)

**Comment by zarrarkhan** [comment]
@brinday Thanks for pointing this out. The maps have been updated to be at a consistent and higher resolution.

```
library(rmap)
rmap::map(mapGCAMReg32, nameAppend="_reg32")
rmap::map(mapGCAMReg32Uruguay, nameAppend="_reg32Uruguay")
```
![map_reg32](https://user-images.githubusercontent.com/7863115/163628959-604f4544-da0c-45cd-a82c-2c3e74b3792e.png)
![map_reg32Uruguay](https://user-images.githubusercontent.com/7863115/163628962-2230a001-e44c-4a6e-a074-9c880140e06d.png)
