### ISSUE TITLE
Adding county-level maps for other countries than the US

### ISSUE THREAD

**Issue by FrancyJGLisboa** [JGCRI/rmap#91]
Hi there. Excellent work! I was wondering if there are plans to add county-level maps for other major nations.

**Comment by zarrarkhan** [comment]
Hi @FrancyJGLisboa!
Thanks for reaching out. Do you have a shape file for the county-level maps you want to use? 
If so please share that with us or let us know which countries and we will look into if we can find appropriate shapefiles for you. 

You can also directly use your own custom map or shapefiles as shown in this example:
https://jgcri.github.io/rmap/articles/vignette_map.html#read-data-from-a-shapefile

Either ways let us know and we will help make this work for you!

Best

Zarrar
